trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure/main.bicep
pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: '<Service Connection Name>'
  resourceGroupName: '<RG Name>'
  location: '<location>'

  # vmName: 'vm-dev-01'
  # adminUsername: 'azureuser'
  # adminPassword will come from a secret variable

stages:
- stage: DeployContainerApps
  displayName: 'Deploy Container Apps using Bicep'
  jobs:
  - job: deploy
    displayName: 'Deploy ContainerApps'
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Validate Bicep template'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: 'Azure'
        inlineScript: |
          echo "Deploying Container Apps to resource group $(resourceGroupName) in $(location)"
          
          az group create \
            --name $(resourceGroupName) \
            --location $(location)
          
          az deployment group what-if \
            --resource-group $(resourceGroupName) \
            --template-file main.bicep \
       
            
    - task: AzureCLI@2
      displayName: 'Deploy Bicep template'
      condition: succeeded()
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: 'Azure'
        inlineScript: |
          echo "Deploying Container Apps to resource group $(resourceGroupName) in $(location)"

          az group create \
            --name $(resourceGroupName) \
            --location $(location)

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file main.bicep \
